#!/bin/bash
set -e

USAGE='dump-token'
DESCRIPTION='
  Decodes a JWT from Haven GRC.
  This is useful for inspecting the claims present in the token when
  working on claim mappers in keycloak.

  Dependencies: requires step command to be installed: try brew install step'

function usage() {
	echo "$USAGE" "$DESCRIPTION" >&2
}

type step >/dev/null 2>&1 || {
	echo >&2 "Error: step cli must be installed. Aborting."
	usage
	exit 1
}
[ $# -eq 0 ] || {
	usage
	exit 1
}

TOKEN=`./get-token`

echo ${TOKEN} | step crypto jwt inspect --insecure 
