#!/bin/bash

set -e

USAGE='report-changed-services'
DESCRIPTION='
  Deploy helper to figure out what services were changed in a merge
  commit. Long term it would be better to use something like bazel,
  but this is good enough for now.

  This does not figure out when docker image base layers have changed,
  it only looks at the files in our monorepo to guess at which services
  have changes.

  We first get a list of all files changed in the merge commit or the
  branch being tested.

  Then, we run a list of checks for each service to see if that service
  has any patterns that match the file list in order to determine if the
  service needs to be deployed.

  Dependencies: requires git to be installed.'

function usage() {
	echo "$USAGE" "$DESCRIPTION" >&2
}

type git >/dev/null 2>&1 || {
	echo >&2 "Error: git must be installed. Aborting."
	usage
	exit 1
}
[ $# -eq 0 ] || {
	usage
	exit 1
}


#var COMMIT_SHA
#COMMIT_SHA=$(git rev-parse HEAD 2> /dev/null)
#MASTER_COMMIT_SHA=$(git rev-parse remotes/origin/master 2> /dev/null)
#CURRENT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2)

declare -A changed_files
if [[ "$" == "master" ]]; then
  # If we are on master, calculate the changes in the merge commit.
  for filename in $(git diff --name-only HEAD^! 2>/dev/null); do
    changed_files["$filename"]=$filename
  done
else
  # If we are not on master, calculate the differences on this branch that are not yet in master
  for filename in $(git diff origin/master... --name-only 2>/dev/null); do
   changed_files["$filename"]=$filename
  done
fi

CHANGE_COUNT=${#changed_files[@]}

if [ "$CHANGE_COUNT" -eq 0 ]; then
  echo 'Did not detect any changed files'
  exit 0
else
  echo "Found $CHANGE_COUNT changed files"
  printf " * %s\n" "${changed_files[@]}"
fi

export DEPLOY_GATEKEEPER=false
export DEPLOY_WEBUI=false
export DEPLOY_KEYCLOAK=false
export DEPLOY_WORKER=false
export DEPLOY_HAVENAPI=false
export DEPLOY_FLYWAY=false
export DEPLOY_FAKTORY=false

for filename in "${changed_files[@]}"; do
  case $filename in
    gatekeeper/*)
      DEPLOY_GATEKEEPER=true
      ;;
    *)
      echo "$filename did not trigger a service deploy"
    ;;
  esac
done




