#!/bin/bash
set -x
docker-compose -f docker-compose.yml -f docker-compose.admin.yml run apitest
docker-compose -f docker-compose.yml -f docker-compose.admin.yml run havenapi buffalo test
docker-compose -f docker-compose.yml -f docker-compose.admin.yml run cypress
