apiVersion: v1
kind: Service
metadata:
  name: havenapi      
spec:
  selector:                  
    service: havenapi
  ports:
  - nodePort: 0
    port: 3000               
    protocol: TCP
    targetPort: 3000
