apiVersion: v1
kind: Service
metadata:
  name: keycloak      
spec:
  selector:                  
    service: keycloak
  ports:
  - nodePort: 0
    port: 8080               
    protocol: TCP
    targetPort: 8080
