development:
  dialect: postgres
  database: mappamundi_dev
  user: postgres
  password: postgres
  host: db
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@db:5432/mappamundi_test?sslmode=disable"}}

production:
  host: {{envOr "DATABASE_HOST" "db"}}
  user: {{envOr "DATABASE_USERNAME" "postgres"}}
  password: {{env "DATABASE_PASSWORD"}}
  database: {{envOr "DATABASE_NAME" "havenstage" }}
  pool: 20
  dialect: postgres
