FROM gobuffalo/buffalo:v0.12.4

RUN mkdir -p $GOPATH/src/github.com/kindlyops/havengrc/havenapi
WORKDIR $GOPATH/src/github.com/kindlyops/havengrc/havenapi
ADD ./havenapi/ $GOPATH/src/github.com/kindlyops/havengrc/havenapi
RUN dep ensure

EXPOSE 3000
ENV ADDR 0.0.0.0
CMD exec buffalo dev
