#!/usr/bin/env Rscript

suppressPackageStartupMessages(library("optparse"))

option_list <- list(
     make_option(c("-t", "--template"), action="store", default="presentation.Rmd"
         help="The template file to use"),
     make_option(c("-d", "--data"), action="store", default="input.csv",
         help="The input data file to use when generating the presentation"),
     make_option(c("-o", "--output"), action="store", default="output.pptx",
         help="The output data file to create")
     )

parse_args2(OptionParser(option_list=option_list))

#rmarkdown::render('report.Rmd',output_file='output.pdf')
